version: "3.8"
services:
  rust:
    container_name: "ahc020"
    build: ./
    volumes:
      - ./:/ahc020:delegated
    ports:
      - 4000:4000
    tty: true
    environment:
      CARGO_TARGET_DIR: /target